version: "3.8"

services:
  postgres:
    image: postgres:latest
    container_name: todo_postgres
    restart: always
    environment:
      POSTGRES_USER: romeo
      POSTGRES_PASSWORD: romeo
      POSTGRES_DB: nexplorehk_todo_list
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgres_data:
